name: CD
on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            SSHPASS: ${{ secrets.APP_PASS }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: APT UPDATE and INSTALL SSHPASS
              run: |
                sudo apt-get update
                sudo apt-get install -y sshpass

            - name: Deploy application
              run: |
                sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} -p 5022 "
                cd laval/ &&
                git pull"

